id: dnsmasq-config

info:
  name: Dnsmasq Config - File Disclosure
  author: DhiyaneshDk
  severity: low
  description: |
    Dnsmasq Config file is exposed.
  reference:
    - https://github.com/imp/dnsmasq/blob/master/dnsmasq.conf.example
  metadata:
    verified: true
    max-request: 1
    fofa-query: body="dnsmasq.conf" && title="index"
  tags: exposure,dnsmasq,files,config

http:
  - method: GET
    path:
      - '{{BaseURL}}/dnsmasq.conf'

    matchers:
      - type: dsl
        dsl:
          - 'status_code == 200'
          - 'contains_any(content_type, "application/octet-stream","application/x-zip-compressed","text/plain")'
          - 'contains_all(body, "server=/","ipset=/")'
        condition: and

      - type: dsl
        dsl:
          - 'status_code == 200'
          - 'contains_any(content_type, "application/octet-stream","application/x-zip-compressed","text/plain")'
          - 'contains_all(body, "dhcp-range=","dhcp-authoritative")'
        condition: and
